version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend # Caminho onde está o Dockerfile do frontend
      dockerfile: Dockerfile
    ports:
      - "5600:80" # Mapeia a porta do host para o container
    restart: always
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photo_battle
    ports:
      - "5460:5432"
    volumes:
      - pstg_data:/var/lib/postgresql/data

volumes:
  pstg_data: